# Generated by Django 6.0.7 on 2026-07-08 23:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, error_messages={'max_decimal_places': 'У суммы должно быть не больше двух знаков после запятой', 'max_digits': 'Введите сумму не больше 999 999 999 999.99 ₽', 'max_whole_digits': 'Введите сумму не больше 999 999 999 999.99 ₽'}, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма'),
        ),
    ]
